name: "ECLAIR push"
on: [workflow_dispatch, push]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WTOKEN: ${{ secrets.WTOKEN }}
jobs:
  Analyze:
    runs-on: eclairit
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Analyze
      run: |
        set -eu
        ./prepare.sh
        cd ECLAIR
        ./analyze.sh
    - name: Analysis log
      if: always()
      run: cat ECLAIR_out/ANALYSIS.log
    - name: Report log
      if: always()
      run: cat ECLAIR_out/REPORT.log
    - name: Publish results
      run: ECLAIR/action_push.sh "${WTOKEN}" ECLAIR_out "${GITHUB_SHA}"
    - name: Upload SARIF
      run: ./ECLAIR/upload.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR_out
