name: "ECLAIR pull request"
on:
  pull_request:
    types: ['opened', 'synchronize']
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Analyze:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Analyze
      env:
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
        PR_BASE_COMMIT_ID: ${{ github.event.pull_request.base.sha }}
        PR_USER: ${{ github.event.pull_request.user.login }}
      run: |
        set -e
        cd ECLAIR
        ../prepare.sh
        ./analyze.sh
        ./action_pull_request.sh out "${GITHUB_SHA}" "${PR_BASE_COMMIT_ID}"
    - name: Upload SARIF
      run: |
        ./ECLAIR/upload.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR/out
