name: "ECLAIR"
on: [workflow_dispatch]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Analyze:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Analyze
      run: |
        set -e
        cd ECLAIR
        gh_ref=$(echo $GITHUB_REF_NAME | sed 's,/,_,')
        # Prepare for build
        ../prepare.sh
        # Analyze the project
        ./analyze.sh
        # Tag database and create badges
        ../db_badge.sh
    - name: Upload SARIF
      run: |
        ./ECLAIR/upload.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR/out
