name: "ECLAIR pull request"
on:
  pull_request:
    types: ['opened', 'synchronize']
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WTOKEN: ${{ secrets.WTOKEN }}
jobs:
  Analyze:
    runs-on: eclairit
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Analyze
      run: |
        set -eu
        ./prepare.sh
        cd ECLAIR
        ./analyze.sh
    - name: Analysis log
      if: always()
      run: cat ECLAIR_out/ANALYSIS.log
    - name: Report log
      if: always()
      run: cat ECLAIR_out/REPORT.log
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR/out
    - name: Publish results
      env:
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
        PR_BASE_COMMIT_ID: ${{ github.event.pull_request.base.sha }}
        PR_USER: ${{ github.event.pull_request.user.login }}
      run: ECLAIR/action_pull_request.sh "${WTOKEN}" ECLAIR_out "${GITHUB_SHA}" "${PR_BASE_COMMIT_ID}"
    - name: Upload SARIF
      run: ./ECLAIR/upload.sh
