name: "ECLAIR"
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: ['opened', 'synchronize', 'edited', 'reopened']
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IS_PR: ${{ github.event_name == 'pull_request' }}
jobs:
  Analyze:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Checkout PR HEAD
      uses: actions/checkout@v3
      if: ${{ github.event_name == 'pull_request' }}
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: ${{ github.event.pull_request.head.sha }}
    - name: Analyze
      run: |
        set -e
        cd ECLAIR
        gh_ref=$(echo $GITHUB_REF_NAME | sed 's,/,_,')

        # PR base and head commits SHAs
        BASE_PR_SHA=${{ github.event.pull_request.base.sha }}
        PR_HEAD_SHA=${{ github.event.pull_request.head.sha }}

        ../prepare.sh

        ANALYSIS_OUTPUT_PATH="ECLAIR/out"
        if [ "${IS_PR} = 'true' ]; then
          ./${PR_HEAD_SHA}/analyze.sh
          ANALYSIS_OUTPUT_PATH="${PR_HEAD_SHA}/ECLAIR/out"
        else
          ./analyze.sh
        fi
        ../tag_db.sh ${ANALYSIS_OUTPUT_PATH}
    - name: Upload SARIF
      run: |
        ./ECLAIR/upload.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR/out
